name: smart_trip_planner_flutter
description: AI-powered trip planner app
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.1
  http: ^1.2.0
  url_launcher: ^6.2.5
  connectivity_plus: ^6.1.5
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/